name: Test tempfile312

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}
  
jobs:
  test:
    name: Run all tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python package
        run: |
          python3 -m pip install .
      - name: Run tests
        run: |
          python3 test/test_tempfile.py
